name: API Calls to FastAPI

on:
  workflow_dispatch:
    inputs:
      endpoint_choice:
        description: "Selecciona un endpoint común"
        required: false
        default: "/api/horario"
        type: choice
        options:
          - /api/horario
          - /api/animes
          - /api/home
          - /api/filters
      endpoint_custom:
        description: "Escribe manualmente un endpoint (ej: /api/one-piece/3)"
        required: false
        default: ""
        type: string

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Determinar endpoint final
        id: set-endpoint
        run: |
          if [ -n "${{ github.event.inputs.endpoint_custom }}" ]; then
            echo "endpoint=${{ github.event.inputs.endpoint_custom }}" >> $GITHUB_OUTPUT
          else
            echo "endpoint=${{ github.event.inputs.endpoint_choice }}" >> $GITHUB_OUTPUT
          fi

      - name: Llamar al endpoint seleccionado
        run: |
          BASE_URL="https://e6f4992833b0.ngrok-free.app"
          ENDPOINT="${{ steps.set-endpoint.outputs.endpoint }}"
          echo "🔗 Llamando a: $BASE_URL$ENDPOINT"
          curl -s "$BASE_URL$ENDPOINT" -H "accept: application/json" -o response.json || echo "{}" > response.json

      - name: Subir respuesta como artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-response
          path: response.json
